Added priv_call functionality to generated contract APIs
hyperledger/firefly-ethconnect pull request #236
Opened 2023-09-02 11:57 UTC by niklas-emmelius-mittelstand-ai

- Retain PrivacyGroupID together with other private transaction fields
- Switch to priv_call when PrivacyGroupID is passed as query option
- No  PrivacyGroupID generation from PrivateFrom and PrivateFor

2023-09-15 20:33 UTC, nguyer requested changes
Thanks @niklas-emmelius-mittelstand-ai for contributing this! I'm happy to merge it. Could you please add a unit test that covers the new code? As is, these changes reduce code coverage and we try to make sure it always goes up. Thanks!

2023-09-18 11:00 UTC, niklas-emmelius-mittelstand-ai commented
Hi, @nguyer I added a test for the changes. Hopefully coverage should now be unchangerd

2024-01-12 20:42 UTC, nguyer requested changes
I am really sorry this one fell off my radar and I didn't see it needed a re-review until now.

2024-01-12 20:42 UTC, nguyer commented on internal/eth/txn_test.go
> +	"github.com/ethereum/go-ethereum/common/hexutil"
Due to the licensing of the `github.com/ethereum/go-ethereum` we cannot depend on it in any code in this repo.

2024-01-12 20:42 UTC, nguyer commented on internal/eth/txn_test.go
> +		Data: &hexutil.Bytes{90, 238, 148, 49},
I think you should be able to change this to `&ethbinding.HexBytes` and have it work, which will remove the need to pull in `github.com/ethereum/go-ethereum`

2024-02-15 18:29 UTC, nguyer commented
Closing this PR due to inactivity. Please feel free to re-open if this work is still ongoing.

2024-02-15 18:29 UTC, closed without merging